### ISSUE TITLE
Control display brightness via OVRAS

### ISSUE THREAD

**Issue by ZenithVal** [Raphiiko/OyasumiVR#28] opened 2023-06-14 09:53 UTC
Open VR Advanced Settings has a brightness slider that's compatible with any headset, it would be neat to make use of this.

[Currently OVRAS does not have an API](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/617) to interact with it yet so this request will be rather open ended until that dream becomes a reality.

**Comment by Raphiiko** [comment] 2023-06-14 09:56
True, it's one of the options mentioned in #14. It would have been the easiest solution really.

However, OyasumiVR 1.8 will be shipping with its own overlay so there isn't any dependency on OVRAS. The overlay itself is already implemented, but the automations for it still have to be written.

Closing as duplicate of #14.

**Closed by Raphiiko** 2023-06-14 09:56 UTC
