### ISSUE TITLE
VRChat mute breaks mute keybind

### ISSUE THREAD

**Issue by Louka3000** [Raphiiko/OyasumiVR#83] opened 2024-04-03 04:20 UTC
When Oyasumi toggles mute in VRChat, either through the debug (Control microphone mute) or when sleep mode is enabled for example, the keybind to mute in VRChat will no longer work, but toggling through the quick menu or action menu will still work.

Turning OSC off in VRChat fixes this. Turning it back on then will still work (keybind will no longer be broken).

/input/voice is only sent once... This doesn't seem to be an issue on OyasumiVR's end as far as I can see, but rather an issue on VRChat's end. Would need to report it on their Canny if you can reproduce it.
In the meantime, (if it's not just a me issue), you could add a warning or tip about this in OyasumiVR's gui.

**Comment by Raphiiko** [comment] 2024-04-03 08:25
I can indeed reproduce this. It seems like their last bug fix hasn't worked completely.

I've submitted a report on their Canny: https://feedback.vrchat.com/bug-reports/p/osc-input-for-input-voice-breaks-keyboard-and-controller-bindings

I don't think this issue is enough to warrant removing the feature entirely like last time, so I'll indeed add a note for it in the next patch/minor update.

**Comment by Raphiiko** [comment] 2024-04-04 16:05
It turns out that in order for other inputs to remain available, VRChat expects it to be reset back to 0 afterwards as well. 

There's a fix for this on develop, it'll land in a patch release soon!

**Closed by Raphiiko** 2024-04-04 16:05 UTC
Labels: VRChat Bug
