### ISSUE TITLE
Logs taking up insane storage

### ISSUE THREAD

**Issue by Cosmiclazers** [Raphiiko/OyasumiVR#78] opened 2024-03-18 07:22 UTC
![image_2024-03-18_031232990](https://github.com/Raphiiko/OyasumiVR/assets/74512638/d18272de-d867-44d1-95bc-c7538ba2f276)
I have been wondering what has been taking up so much storage over the past few months. I've been kinda ignoring it up until now, but I just did a quick scan on wiztree, and I saw that oyasumi logs are taking up 210 gigabytes ;-;
Obviously the quick scan is not super accurate, but after deleting the files I have freed up 120GB of storage. Before removing these, I did make sure to delete the event logs in oyasumi, but that did nothing.
It would be nice to:
A) Have unneeded logs removed (I don't know exactly what all of these logs are used for, but I'd be surprised if all necessary items got anywhere near even a single gigabyte.
B) Have a way to remove logs in the app without having to manually go in through file explorer, or some other program.
(FYI, i'm not very active on github. I'll check back here every once in a while for responses, but if you ask for more info, and I don't respond, feel free to add me in discord - cosmiclazers)

**Comment by Raphiiko** [comment] 2024-03-18 07:39
Hey! That's indeed slightly concerning. I should probably add some functionality to automatically clean up older log files. 

This _is_ already possible manually, in the advanced settings: 
<img src="https://github.com/Raphiiko/OyasumiVR/assets/111654848/497bcbae-8d3f-4aac-b500-296c54d0ea21" width="200" />

However, what's more concerning to me is why these have even grown this much in the first place, as even after some months it really shouldn't add up to more than just a couple of megabytes. I assume you already deleted them, but the next time a log file grows over 2MB in size, could you give it a quick check for me? It's quite likely that something is being spammed to the log which is causing them to grow this large.

**Comment by Cosmiclazers** [comment] 2024-03-18 07:47
yeah, I'll check when it gets to that size. I do have frequent internet disconnects, so maybe it is something with that? If reconnection attempts happen every second or so in a 2 hour disconnect, that could definitely add up.

**Comment by Raphiiko** [comment] 2024-03-18 08:16
Confirmed on Discord this log spam is caused by the ongoing issue with MDNS advertisements.

**Comment by Raphiiko** [comment] 2024-03-21 15:10
Closing, as this bug is now tracked in #80.

**Closed by Raphiiko** 2024-03-21 15:10 UTC
